import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import { Toaster } from '~/components/ui/sonner'
import TemplateSwitcher from '~/components/ui/templateSwitcher'
import './globals.css'

const nunito = Nunito({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning className={` ${nunito.className} antialiased`}>
        {children}
        <TemplateSwitcher />
        <Toaster richColors closeButton />
      </body>
    </html>
  )
}
